name: Notify Central

on:
  push:  # or workflow_dispatch

jobs:
  trigger-run-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch event to centralrepo repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.CENTRAL_PAT }}" \
            https://api.github.com/repos/pnamilak/centralrepo/dispatches \
            -d '{"event_type":"sql_update","client_payload":{"repo":"pnamilak/sql_update"}}'
