name: Notify Central Repo

on:
  push:
    paths:
      - '**.sql'

jobs:
  notify:
    runs-on: self-hosted

    steps:
      - name: Notify centralrepo about SQL update
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.CENTRAL_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/pnamilak/centralrepo/dispatches \
            -d '{"event_type":"sql_update","client_payload":{"repo":"'"${{ github.repository }}"'"}}'
