name: Notify Central

on:
  push:
    paths:
      - '**/*.sql'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger central runner
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.CENTRAL_PAT }}" \
            https://api.github.com/repos/pnamilak/sql-central-runner/dispatches \
            -d '{"event_type":"sql_update","client_payload":{"repo":"'"${{ github.repository }}"'"}}'
